# -*- coding: utf-8 -*-
"""Batalha dos algoritmos Marcelo e Felipe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1il09xj7gPD6vD9RvWSJxbSf1nP7Cau79
"""

#eu não consegui fazer com que a variavel casareal se mantesse durante as repetições do while, por isso as casas não avançam.
import random
import time
import copy
casa_atual = 0
casareal = 0
def casareal(whiles):
  return casareal
whiles = []
matriz = [[15,14,13,"  -",1],[16,"  -",12,"  -",2],[17,"  -",11,"  -",3],[18,"  -",10,"  -",4],[19,"  -",9,"  -",5],["Final","  -",8,7,6]]

# se você chamar essa função ela imprimirá a matriz de uma maneira similar a uma tabela
def imprimir_matriz(matriz):
  s = [["Casa " + str(e) if (e != 0 and e!= "  -") else str(e) for e in row] for row in matriz]
  lens = [max(map(len, col)) for col in zip(*s)]
  fmt = '\t'.join('{{:{}}}'.format(x) for x in lens)
  table = [fmt.format(*row) for row in s]
  print("\n=----------------CORRIDA-A-PÉ-----------------= \n")
  print('\n'.join(table))
final = 0
def verificar_ganhador(matriz):
  # aqui você pode colocar a lógica para verificar se o jogo terminou 
  if(casareal > 19):
   ganhou = True
#  if final == 1 :
#    return print(f'Parabéns, {jogador1} ganhou o jogo!')
#  if final == 2 :
#    return print(f'Parabéns, {jogador2} ganhou o jogo!')
def respostajogador(whiles):
        jogadorvez= input(f"Está na vez de qual jogador? (digite 'P1' para {jogador1} ou 'P2' para {jogador2}. ")
        if(jogadorvez == "P1"):
          resposta = input(f"Deseja jogar o dado, {jogador1} ? (digite 'S' para sim e qualquer outra coisa para não: ")

        if(jogadorvez == "P2"):
          resposta = input(f"Deseja jogar o dado, {jogador2} ? (digite 'S' para sim e qualquer outra coisa para não: ")
        if(resposta == "S"):
          resposta = True
          dado = random.randint(1,6)
          print(f"Dado jogado, deu {dado}.\nAndando {dado} casas para frente.")    
          time.sleep(1)
          def casareal(whiles):
            return casareal
          casareal(whiles)
          casareal =+ casa_atual + dado
          print(f"Jogador {jogadorvez} parou na casa {casareal}.")
        elif(jogadorvez) != "P1" or "P2" and (resposta) != "S" :
          print("Resposta inválida, insira uma resposta válida.")
          time.sleep(1)
          for dado in imprimir_matriz : matriz.append(int);
        if(casareal > 19):
          ganhou = True

print("O tabuleiro tem uma tamanho de 5 por 6")

imprimir_matriz(matriz)

ganhou = False

jogador1 = input("\nJogador 1, Qual seu nome? ")
jogador2 = input("\nJogador 2, Qual seu nome? ")

vez = ''
print(f"\nOK,Vamos jogar {jogador1} e {jogador2}.")
dado = random.randint(1,6)

ganhou = False
while ganhou == False:
  imprimir_matriz(matriz)
  respostajogador(whiles)

def copiar (imprimir_matriz): # funcao para copiar elementos de lista/tupla gerando lista nova
  imprimir_matriz(matriz)