# -*- coding: utf-8 -*-
"""Churrasco.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dqqJX9A1FhaS86wOzgM9eey47leeXjhK

Fabiano, coordenador do curso de computação convidou os alunos para um Churrasco. Porém, precisamos organizar algumas listas, sendo: a lista de quem participará, dentre estes aqueles que bebem e dentre eles os veganos.

Começaremos montando as estruturas de dados para acomodar estas listas
"""

presentes = []
bebem = []
veganos = 0

controle = True

while(controle == True):
  nome = input("Digite o nome da pessoa ")
  vai = input("Vai no churrasco? (S ou N)")
  if (vai == "S"):
    presentes.append(nome)
    bebe = input("A pessoa bebe? (S ou N) ")
    if (bebe == 'S'):
      bebem.append(nome)
      maior_de_18 = input("A pessoa é maior de idade (S ou N)? ")
      if(maior_de_18 == "N"):
        bebem.remove(nome)
  
  continuar = input("Quer adicionar mais pessoas? (S ou N)")
  if(continuar == 'S'):
    controle = True
  else:
    controle = False

carne = len(presentes) * 400
refrigerante = len(bebem) * 2

print("Compre ", carne, " kgs de carne e ", refrigerante, " litros de refrigerante")

presentes

bebem

for pessoa in presentes:
  print(pessoa)

while(len(presentes) > 0):
  chegou = input("Digite o nome de quem chegou")
  try:
    presentes.remove(chegou)
  except:
    print(chegou, "é um penetra")