# -*- coding: utf-8 -*-
"""ListaAtividadesMatriz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UpGu68dYhulUCYc6EGjUSM_GIKNLfNA6

1. Faça um programa que preencha uma matriz M (2 X 2), calcule e mostre a matriz R, 
resultante da multiplicação dos elementos de M pelo seu maior elemento

## versão 1
"""

M = [ [0,0] , [0,0] ]
R = [ [0,0] , [0,0] ]


#solicitando os valores, percorrendo a matriz
for i in range(2):
  for j in range(2):
    M[i][j] = int( input("Digite um valor:") )

#encontrando o maior
maior = -100000
for i in range(2):
  for j in range(2):
    if (M[i][j] > maior):
      maior = M[i][j]

# multiplicando os valores para armazenar em R
for i in range(2):
  for j in range(2):
    R[i][j] = M[i][j] * maior

print (M)
print (R)

"""## versão 2"""

M = [ [0,0] , [0,0] ]
R = [ [0,0] , [0,0] ]


#solicitando os valores, percorrendo a matriz
maior = -100000
for i in range(2):
  for j in range(2):
    M[i][j] = int( input("Digite um valor:") )
    if (M[i][j] > maior):
      maior = M[i][j]    

# multiplicando os valores para armazenar em R
for i in range(2):
  for j in range(2):
    R[i][j] = M[i][j] * maior

print (M)
print (R)

"""2. Faça um programa que preencha uma matriz 10 X 3 com as notas de dez alunos em 
três provas. O programa deverá mostrar um relatório com o número dos alunos (linha) 
e a prova em que cada aluno obteve a menor nota. Ao final do relatório, deverá 
mostrar quantos alunos tiveram menor nota em cada uma das provas: na prova 1, 
prova 2 e prova 3

"""

import numpy as np
import random

notas = np.zeros(shape=(10,3))
menores_notas_prova = [ 0, 0, 0 ]

for numero_aluno in range(10):
  for nota_aluno in range(3):
    print("Digite a nota ", nota_aluno, "para o aluno ", numero_aluno, ": ")
    notas[numero_aluno][nota_aluno] = float( input() )

print(notas)

for numero_aluno in range(10):
  prova = 0
  menor = 11
  for nota_aluno in range(3):
    if (notas[numero_aluno][nota_aluno] < menor):      
      menor = notas[numero_aluno][nota_aluno]
      prova = nota_aluno
  print("ALUNO ", numero_aluno)
  print("MENOR NOTA NA PROVA ", prova , "COM NOTA ", menor)
  menores_notas_prova[prova] += 1

for i in range(3):
  print("Alunos que tiveram menor nota na prova ", i, ": ", menores_notas_prova[i])

"""4. Crie um programa que preencha uma matriz 10X20 com números inteiros e some cada 
umas das linhas, armazenando o resultado das somas em um vetor. A seguir, o 
programa deverá multiplicar cada elemento da matriz pela soma da linha 
correspondente e mostrar a matriz resultante.
"""

import random

mat = [ [0]*20 ] * 10
soma = [0]*10

for i in range(0,10):
  for j in range(0,20):
    mat[i][j] = random.randint(1,10) #preenchi com valores aleatórios para não ter que digitar todos
    soma[i] = soma[i] + mat[i][j]


for i in range(0,10):
  for j in range(0,20):
    mat[i][j] = mat[i][j] * soma[i]

for i in range(0,10):
  for j in range(0,20):
    print(f"{i} - {j}:", mat[i][j])