# -*- coding: utf-8 -*-
"""Lista Atividades 9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XIfeF93NRP-BxGDrtytTYr4eHh3Aq4mc
"""

numeros = []

for i in range(9):
  num = input("Digite um número inteiro ")
  numeros.append(int(num))

def primo(n):
    for val in range(2,n):
        if n % val == 0:
            return False

    return True

numeros = []
primos = []
posicoes = []

for i in range(0,9):
    numero  = int(input("Digite o número"))
    numeros.append(numero)
    if (primo(numero)):
        primos.append(numero)
        posicoes.append(i)

for j in range(0,len(primos)):
    print("O número", primos[j], ' está na posição', posicoes[j])
    
for primo in primos:
    posicao = numeros.index(primo)
    print("O primo ", primo, "está na posição ", posicao)

def primo(n):
    for val in range(2,n):
        if n % val == 0:
            return False
    return True

numeros = [7,5,3,2,6,7,8,9,10]
primos = []

for numero in numeros:
  if (primo(numero) == True):
    primos.append(numero)

for primo in primos:
  print("O número ", primo, " é primo")
  posicao = numeros.index(primo)
  print("Ele está na posição ", posicao)



"""ATIVIDADE 2"""

salario_vendedor = 545
porcentagem = 5
objetos = ["Copo","Faca","Tesoura","Bombril","PC","Mouse","Canivete","Coca","Pamonha","Polenta"]
valor_unitario = []
quantidade_vendida = []

for objeto in objetos:
  print("ITEM: ", objeto)
  vlr = float(input("Qual o valor unitário?"))
  valor_unitario.append(vlr)
  qtd = int(input("Qtos foram vendidos"))
  quantidade_vendida.append(qtd)

print("RElatório")
print("Objeto | Qtd | Vlr Unitário | Valor Total ")
for i in (range(0,len(objetos))):
  print(objetos[i], " | ", valor_unitario[i], " | ", quantidade_vendida[i], " | ", quantidade_vendida[i] * valor_unitario[i1])

