# -*- coding: utf-8 -*-
"""prova.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t3Zcw31D9ZvYFLj17OkjODz6MMC6n20x
"""

n = input("Digite o seu nome: ")

an = int( input("Digite o ano de nascimento: ") )

at = 2021

i = at - an

print ( "Olá ", n, ", você tem ", i, " anos" )

n1 = input ( "Digite a nota 1" )
n2 = input ( "Digite a nota 2" )
n3 = input ( "Digite a nota 3" )

m = (float(n1) * 2 + float(n2) * 4 + float(n3) * 6 ) / ( 2 + 4 + 6 )

print ("A média final é ", m)

cf = float( input("Digite o custo de fábrica: ") )

imposto = 45 / 100

p_dist = 28 / 100

cc = cf + (cf * imposto)

print(cc)