# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dgMdq4hRo6AIqw7tCMA-mUv4P8CHH-YS
"""

nome= input ("digite aqui seu nome")
nascimento= int (input("digite aqui sua data de nascimento"))

idade= int(2022-nascimento)
print ("olá,",nome,"você tem",idade,"anos")

nota1= float (input("nota 1"))
peso1= float (input("peso 1"))

nota2= float (input("nota 2"))
peso2= float (input("peso 2"))

nota3= float (input("nota 3"))
peso3= float (input("peso 3"))



media= (nota1*peso1 + nota2*peso2 + nota3*peso3) / (peso1+peso2+peso3)

print("média:",media)

custo_do_carro = float (input("custo carro"))

distribuidor = float(int(custo_do_carro) / (100) * (28))
imposto = float(int(custo_do_carro)/ (100) * (45))

valorfinal= (custo_do_carro+distribuidor+imposto)

print(valorfinal)

opcoes = {
    "1": "Refrigerante de cola",
    "2": "Batata-frita",
    "3": "Barra de cereal",
    "4": "Água",
    "5": "Água com gás",
    "6": "Achocolatado",
    "7": "Bala de Menta",    
}

status = "AGUARDANDO"


while ( status == "AGUARDANDO" ):
  opcao = input( "Digite INICIAR para escolher um produto: " )
  if ( opcao != "INICIAR" ):
    print( "Você Digitou uma opção inválida, o programa terminou!" )
    status = "FINALIZADO"
  else:
    print( "Escolha um produto: " )
  
    for chave, valor in opcoes.items():
      print( chave + " = " + valor )
  
    print( "ou digite CANCELAR para retornar ao começo" )

    opcao = input("Digite o código do produto: ")

    if ( opcao != "CANCELAR" ):
      if ( opcao in opcoes ):
        print( "Você escolheu " + opcoes[opcao])
        confirmacao = input( "Digite CONFIRMAR para receber o produto: " )
        if (confirmacao == "CONFIRMAR"):
          print( "Obrigado por usar nossa máquina!" ) 
      else:
        print("Esse produto não existe")