# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VIVk1n297uUt3KmOE6fc3gLdZHm3uhx7
"""

quantidades = []
valores_unitarios = [
    1.9,
    2.12,
    1.99,
    3.50,
    4.40,
    6.90,
    10.80,
    0.01,
    0.50,
    10.00
]

for contador in range(0,10):
    valor = valores_unitarios[contador]
    qtd = int (input(f"Digite valor para {valor}"))
    quantidades.append(qtd)

print (valores_unitarios)
print (quantidades)  

total_vendas = 0

for i in range(0,10):
  valor_total = quantidades[i] * valores_unitarios[i]
  total_vendas = total_vendas + valor_total
  print ("Produto ", i )
  print ("Quantidade: ", quantidades[i])
  print ("Valor Unitário: ", valores_unitarios[i])
  print ("Valor Total: ", valor_total)
  print ("-----------------------------")

print ("Valor total das vendas ", total_vendas)

comissao = total_vendas * (5 / 100 )

print ("O vendedor ganhará ", comissao, " de comissão ")

mais_vendido = max(quantidades)

posicao_valor = quantidades.index(mais_vendido)

print ("A posição do mais vendido é ", posicao_valor)
print ("O valor dele é ", valores_unitarios[posicao_valor])